import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Container } from '@mui/material'
import Header from '@/views/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>SwiftRelay - Relay Auto Booker Refresher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainPage}>
        <div>asmdnkf</div>
        <nav className={styles.navbar}>
          <Container>
            <Header />
          </Container>
        </nav>
        <main className={styles.main}>
          red
        </main>
        <footer className={styles.footer}>
          FOOTER
        </footer>
      </div>

    </>
  )
}
