import Head from 'next/head'

import { Box } from '@mui/material'
import Navbar from '@/views/Navbar'
import Header from '@/views/Header'
import HowItWorks from '@/views/HowItWorks'
import Features from '@/views/Features'
import UiDesign from '@/views/UiDesign'
import Testimonials from '@/views/Testimonials'
import Subscription from '@/views/Subscription'
import Faq from '@/views/Faq'
import Banner from '@/views/Banner'
import Footer from '@/views/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>SwiftRelay - Relay Auto Booker Refresher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ minHeight: '100vh', position: 'relative', }}>
        <Box component={'nav'} sx={{
          height: '100px', background: "#fff",
          display: 'flex', alignItems: 'center',
          // position: 'sticky', top: 0, zIndex: 100,
        }}>
          <Navbar />
        </Box>
        <Box component='main' sx={{ minHeight: 'calc(100vh - 100px - 260px)', position: 'relative', }}>
          <Header />
          <HowItWorks />
          <Features />
          <UiDesign />
          <Testimonials />
          <Subscription />
          <Faq />
          <Banner />
        </Box>
        <Box component={'footer'} sx={{ height: '260px', background: "#F7F7F7" }}>
          <Footer />
        </Box>
      </Box>

    </>
  )
}
